---
config:
  vpc:
    name: nginx_demo
    cidr: 10.0.0.0/16
    dopt_name: nginx_demo_dopts
    alb:
      nginx_demo_alb:
        name: nginx-demo-lb
        sg: nginx_demo_alb_sg
        subnets: nginx_demo_pub_rt
        target_group_name: nginx-demo-lb-tg
    ecs:
      cluster:
        name: nginx_demo_ecs_cluster
      task_definition:
        name: nginx_demo_taskdef
      service:
        name: nginx_demo_service
    sgs:
      nginx_demo_alb_sg:
        name: nginx_demo_alb_sg
        description: Security group for the load balancer
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_name: nginx_demo_ecs_sg
            group_desc: Security group for the container hosts
      nginx_demo_ecs_sg:
        name: nginx_demo_ecs_sg
        description: Security group for the container hosts
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_name: nginx_demo_alb_sg
            group_desc: Security group for the load balancer
        rules_egress:
          - proto: tcp
            from_port: 53
            to_port: 53
            cidr_ip: 0.0.0.0/0
          - proto: udp
            from_port: 53
            to_port: 53
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0            
    igws:
      nginx_demo_igw:
        name: nginx_demo_igw
    rtbs:
      nginx_demo_main_rt:
        name: nginx_demo_main_rt
        main: true
      nginx_demo_pub_rt:
        name: nginx_demo_pub_rt
        gateway: nginx_demo_igw
      nginx_demo_priv_az_a_rt:
        name: nginx_demo_priv_az_a_rt
        gateway: nginx_demo_priv_az_a_ng
      nginx_demo_priv_az_b_rt:
        name: nginx_demo_priv_az_b_rt
        gateway: nginx_demo_priv_az_b_ng
      nginx_demo_priv_az_c_rt:
        name: nginx_demo_priv_az_c_rt
        gateway: nginx_demo_priv_az_c_ng
    subnets:
      nginx_demo_pub_az_a:
        name: nginx_demo_pub_az_a
        cidr: 10.0.1.0/24
        route_table: nginx_demo_pub_rt
        az: A
      nginx_demo_pub_az_b:
        name: nginx_demo_pub_az_b
        cidr: 10.0.2.0/24
        route_table: nginx_demo_pub_rt
        az: B
      nginx_demo_pub_az_c:
        name: nginx_demo_pub_az_c
        cidr: 10.0.3.0/24
        route_table: nginx_demo_pub_rt
        az: C
      nginx_demo_priv_az_a:
        name: nginx_demo_priv_az_a
        cidr: 10.0.11.0/24
        route_table: nginx_demo_priv_az_a_rt
        az: A
      nginx_demo_priv_az_b:
        name: nginx_demo_priv_az_b
        cidr: 10.0.12.0/24
        route_table: nginx_demo_priv_az_b_rt
        az: B
      nginx_demo_priv_az_c:
        name: nginx_demo_priv_az_c
        cidr: 10.0.13.0/24
        route_table: nginx_demo_priv_az_c_rt
        az: C
    eips:
      nginx_demo_pub_az_a_eip:
        name: nginx_demo_pub_az_a_eip
      nginx_demo_pub_az_b_eip:
        name: nginx_demo_pub_az_b_eip
      nginx_demo_pub_az_c_eip:
        name: nginx_demo_pub_az_c_eip
    ngws:
      nginx_demo_priv_az_a_ng:
        name: nginx_demo_priv_az_a_ng
        subnet: nginx_demo_pub_az_a
        eip: nginx_demo_pub_az_a_eip
      nginx_demo_priv_az_b_ng:
        name: nginx_demo_priv_az_b_ng
        subnet: nginx_demo_pub_az_b
        eip: nginx_demo_pub_az_b_eip        
      nginx_demo_priv_az_c_ng:
        name: nginx_demo_priv_az_c_ng
        subnet: nginx_demo_pub_az_c
        eip: nginx_demo_pub_az_c_eip        
