---
- name: Create nginx-demo
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Copy config to state
      ansible.builtin.set_fact:
        state: "{{ config }}"

    - name: Gather regions AZ's
      ansible.builtin.import_tasks:
        file: tasks/gatherazs.yml

    - name: Create VPC
      ansible.builtin.import_tasks:
        file: tasks/createvpc.yml

    - name: Create App
      ansible.builtin.import_tasks:
        file: tasks/createapp.yml

    - name: Final state dump
      ansible.builtin.debug:
        msg: "{{ state }}"

    - name: Info dump to user
      ansible.builtin.debug:
        msg:
          - "------ Find the app deployed here ---------"
          - "http://{{ state.vpc.alb.nginx_demo_alb.dns }}"
          - "------ Find the app deployed here ---------"
...
