---
- name: Create nginx-demo
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Copy config to state
      ansible.builtin.set_fact:
        state: "{{ config }}"

    - name: Gather regions AZ's
      ansible.builtin.import_tasks:
        file: tasks/gatherazs.yml

    - name: Create VPC
      ansible.builtin.import_tasks:
        file: tasks/createvpc.yml

    - name: Final state dump
      ansible.builtin.debug:
        msg: "{{ state }}"
