---
- name: Create nginx-demo
  hosts: localhost
  gather_facts: false
  tasks:
  
    - name: Find internet gateways
      amazon.aws.ec2_vpc_igw_info:
        filters:
          "tag:Name": "{{ config.vpc.igw }}"
      register: runstateigw
    - name: Delete internet gateway
      amazon.aws.ec2_vpc_igw:
        internet_gateway_id: "{{ item.internet_gateway_id }}"
        state: absent
      loop: "{{ runstateigw.internet_gateways }}"
    - name: Find our VPC
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Name": "{{ config.vpc.name }}"
      register: runstatevpc
    - name: Delete our VPC
      # when: 0 > 1
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ item.id }}"
        state: absent
      loop: "{{ runstatevpc.vpcs }}"
    - name: Delete DHCP option set
      amazon.aws.ec2_vpc_dhcp_option:
        dhcp_options_id: "{{ item.dhcp_options_id }}"
        state: absent
      loop: "{{ runstatevpc.vpcs }}"
