---
- name: Gather VPC state
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ state.vpc.name }}"
  register: result

- name: Dump VPC info into state
  ansible.builtin.set_fact:
    state: "{{ state | combine({'vpc': {item.key: item.value}}, recursive=true) }}"
  loop:
    - { key: 'vpcid', value: "{{ result.vpcs[0].vpc_id }}" }
    - { key: 'dopt_id', value: "{{ result.vpcs[0].dhcp_options_id }}" }

- name: Gather region info
  amazon.aws.aws_az_info:
  register: result

- name: Dump VPC info into state
  ansible.builtin.set_fact:
    state: "{{ state | combine({'vpc': {item.key: item.value}}, recursive=true) }}"
  loop:
    - { key: 'region_name', value: "{{ result.availability_zones[0].region_name }}" }

- name: Gather internet gateway info
  amazon.aws.ec2_vpc_igw_info:
    region: "{{ state.vpc.region_name }}"
    filters:
      "tag:Name": "{{ state.vpc.igws.nginx_demo_igw.name }}"
  register: result

- name: Dump internet gateway info into state
  ansible.builtin.set_fact:
    state: "{{ state | combine({'vpc': {'igws': {'nginx_demo_igw': {item.key: item.value}}}}, recursive=true) }}"
  loop:
    - { key: 'id', value: "{{ result.internet_gateways[0].internet_gateway_id }}" }

- name: Gather subnet info
  amazon.aws.ec2_vpc_subnet_info:

- name: Dump results
  ansible.builtin.debug:
    var: state
